local home    = os.getenv("HOME")
local version = myModuleVersion()
local pkgName = myModuleName()
local base     = pathJoin(home,"sw","x86_64","firestarter-metric-metricq")
prereq("FIRESTARTER")
depends_on("metricq")
load("gcc")
prepend_path("LD_LIBRARY_PATH", base)
setenv("FIRESTARTER_METRIC_METRICQ_DUMPER", pathJoin(base,"metric-metricq-dumper"))
